server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:/study/msa/msa-sample/git-local-repo
          default-label: main