server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:/study/msa/msa-sample/git-local-repo
          uri: https://github.com/pebblepark/spring-cloud-config.git
          default-label: main